#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://devantler.com" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - flexible_include
  - premonition

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed







