title: Nikolai Emil | Devantler
author:
  name: Nikolai Emil Damm
  email: ned@devantler.com
description: >-
  I am an ambitious software engineer with an agile mindset, and the desire to overcome innovative challenges. For that open source is my toolbox 🧰
timezone: Europe/Copenhagen
github_username:  devantler
linkedin_username: nikolai-emil-damm-14a786150

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/devantler"
      title: GitHub
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/nikolai-emil-damm-14a786150/"
      title: LinkedIn
    - platform: credly
      user_url: "https://www.credly.com/users/nikolai-emil-damm"
      title: Credly
show_excerpts: false
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-remote-include

exclude:
  - .github/
  - .vscode/
  - github-configuration/
  - projects/
  - .editorconfig
  - .gitmodules
