#-------------------------------
# Site Settings
title: Nikolai Emil | Devantler
logo: # You can add own logo. For example '/images/logo.png'.
description: >-
  I am an ambitious software engineer with an agile mindset, and the desire to overcome innovative challenges. For that open source is my toolbox 🧰

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About Me'
      url: '/cv'
    - title: 'Projects'
      url: '/projects'
    - title: 'libraries'
      url: '/libraries'
    - title: 'Templates'
      url: '/templates'
    - title: 'Contact Me'
      url: '/contact'

#-------------------------------
# Author Settings
author:
  name: Nikolai Emil Damm
  avatar: 'assets/images/author.png'

#-------------------------------
# Hero Settings
hero:
  title: Nikolai Emil Damm
  description: Commit, Push, Deploy, Repeat
  image: 'assets/images/ocean.jpg'

#-------------------------------
# Contact Settings
contact:
  email: xyzgkkww # Add your email for contact form
  description: Feel free to contact me for any queries or collaboration.

#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/nikolai-emil-damm-14a786150/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/devantler"}

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: devantler # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
# google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
#mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
# mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
# mailchimp-button-text: Join
