name: "TODOs"
on:
  push:
    branches: [main]

jobs:
  call-todos-workflow:
    uses: devantler-tech/.github/.github/workflows/todos.yaml@main
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
